var friendsAge = [15,16,17,19];
// console.log(friendsAge);
console.log(friendsAge[0]);
friendsAge[3] = 25;
console.log(friendsAge);
var position = friendsAge.indexOf(16);
console.log(position);
var pos2 = friendsAge.indexOf(25);
console.log(pos2);
friendsAge.push(18);
console.log(friendsAge);
var sss = friendsAge.length;
console.log(sss);
friendsAge.pop();
console.log(friendsAge);
friendsAge.unshift(11,10);
console.log(friendsAge);
friendsAge.shift();
console.log(friendsAge);

var tealine = ["aa","bb","cc","dd","ee","ff"];
console.log(tealine);
tealine.push("tt");
console.log(tealine);
tealine.pop();
console.log(tealine);
tealine.shift();
console.log(tealine);
tealine.unshift("zz");
console.log(tealine);
var part = tealine.slice(2,4);
console.log(part);