console.log(19);
var applePrice = 120;
console.log(applePrice);
console.log(typeof applePrice);
var name = 'Sultana "Tasnim" Jahan';
console.log(name);
console.log(typeof name);
console.log()
var isHot = true;
console.log(isHot);
console.log(typeof isHot);
var promise = "Hi I am Tasnim. I PROMISE to be a GOOD GIRL. and never be a lazy or bad girl";
console.log(promise.indexOf("Tas"));
console.log(promise.toUpperCase());
console.log(promise.split(' '));
var number1 = 19.7;
var number2 = '19';
// number2 = parseFloat(number2);
// number2 = +number2
console.log(number1 + +number2);
var number3 = 25;
number3 = ''+number3;
console.log(typeof number3);
var number4 = 0.1;
var number5 = 0.4;
var total = number4+number5;
total = total.toFixed(3);
console.log(total);
var firstName = "Sultana";
var lastName = "Jahan";
var fullName ="My "+ firstName + " is " + lastName;
console.log(fullName +" and me");

var no=5.28;
var absolutelNumber = Math.abs(no);
console.log(absolutelNumber);
var approximateValue = Math.round(no);
console.log(approximateValue);
var upperValue = Math.floor(no);
console.log(upperValue);
var randomNumber = Math.random();
randomNumber = randomNumber.toFixed(3);
console.log(randomNumber);